//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_megaperfume2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUTORS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISTRIBUTORS()
        {
            this.PRICES = new HashSet<PRICES>();
        }
    
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<bool> GOINPURCHASELIST { get; set; }
        public Nullable<bool> FIRSTALWAYS { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> SENDMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string COMMENT { get; set; }
        public Nullable<byte> PRIORITY { get; set; }
        public Nullable<int> DEALERORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRICES> PRICES { get; set; }
    }
}
