//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_megaperfume2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRICES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRICES()
        {
            this.PRICESRECORDS = new HashSet<PRICESRECORDS>();
        }
    
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.Guid> DISID { get; set; }
        public double DISCOUNT { get; set; }
        public byte DEFAULTCURRENCY { get; set; }
        public double TURNDOLLARSRATE { get; set; }
        public string SHEET { get; set; }
        public string NAMERANGE { get; set; }
        public string PRICERANGE { get; set; }
        public int FIRSTROW { get; set; }
        public float MAXPRICECHANGE { get; set; }
        public string STOPWORDS { get; set; }
        public string FILENAME { get; set; }
        public Nullable<System.DateTime> FILEDATE { get; set; }
        public string FILESHEETS { get; set; }
        public string COMMENT { get; set; }
        public string SKURANGE { get; set; }
        public string STOCKRANGE { get; set; }
        public string INSTOCKRANGE { get; set; }
    
        public virtual DISTRIBUTORS DISTRIBUTORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRICESRECORDS> PRICESRECORDS { get; set; }
    }
}
