//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_megaperfume2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTS()
        {
            this.LINKS = new HashSet<LINKS>();
        }
    
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public System.Guid MANID { get; set; }
        public double PRICE { get; set; }
        public Nullable<double> BASEPRICE { get; set; }
        public string LABEL { get; set; }
        public string PARENTLABEL { get; set; }
        public byte STATE { get; set; }
        public bool USERCHANGED { get; set; }
        public bool EXTRAUSED { get; set; }
        public int EXTRA { get; set; }
        public bool AUTOUPDATE { get; set; }
        public Nullable<bool> AUTOUPDATETESTS { get; set; }
        public Nullable<bool> PRODUCTEXISTS { get; set; }
        public bool PHOTOEXISTS { get; set; }
        public int VIEWSTYLEID { get; set; }
        public string CHILDNAME { get; set; }
        public bool TESTER { get; set; }
        public bool PUBLISHED { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public System.DateTime CHANGEDATE { get; set; }
        public byte CORRECTEDSTATUS { get; set; }
        public int INSTOCK { get; set; }
        public bool ISPROBIRKA { get; set; }
        public string COMMENT { get; set; }
        public bool DELETED { get; set; }
        public bool IS_PROMO { get; set; }
        public int TEMPLATEID { get; set; }
        public int SKU { get; set; }
        public bool ISNEW { get; set; }
        public Nullable<System.DateTime> ISNEWSTARTDATE { get; set; }
        public double WEIGHT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINKS> LINKS { get; set; }
        public virtual MANUFACTURERS MANUFACTURERS { get; set; }
    }
}
